export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';

export const FETCH_BALEFIRE_PAGE = 'FETCH_BALEFIRE_PAGE';
export const FETCH_BALEFIRE_PAGE_SUCCESS = 'FETCH_BALEFIRE_PAGE_SUCCESS';
export const FETCH_BALEFIRE_PAGE_FAIL = 'FETCH_BALEFIRE_PAGE_FAIL';

export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAIL = 'FETCH_COLLECTION_FAIL';

export const FETCH_LISTINGS = 'FETCH_LISTINGS';
export const FETCH_LISTINGS_SUCCESS = 'FETCH_LISTINGS_SUCCESS';
export const FETCH_LISTINGS_FAIL = 'FETCH_LISTINGS_FAIL';

export const SET_USER_GEO = 'SET_USER_GEO';
export const SET_USER_GEO_SUCCESS = 'SET_USER_GEO_SUCCESS';
export const SET_USER_GEO_FAIL = 'SET_USER_GEO_FAIL';
